name: 'warehouse'
version: '1.1.33'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Paths to files:

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Models in this project: 

models:
    warehouse: 
        staging:
            +materialized: view
            google_calendar:
                stg_google_calendar_dim:
                    +enabled: true
            ebird:
                stg_ebird:
                    +enabled: true
            covid:
                stg_county_cases:
                    +enabled: true
                stg_county_mask_use:
                    +enabled: true
                stg_excess_deaths:
                    +enabled: true
        intermediate:
            +materialized: view
            google_calendar:
                int_google_calendar_dim:
                    +enabled: true
            ebird:
                int_ebird:
                    +enabled: true
            covid: 
                int_county_cases:
                    +enabled: true
        prod_dw:
            +materialized: view
            google_calendar:
                google_calendar_dim:
                    +enabled: true
            ebird: 
                ebird:
                    +enabled: true
            covid:
                county_cases:
                    enabled: true


# Packages applied to this project:

packages:
  - package: dbt-labs/dbt_external_tables
    version: 0.7.0
        