name: 'warehouse'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: default

# Paths to files:

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Models in this project: 

models:
    warehouse: 
        +persist_docs:
            relation: true
            columns: true
        staging:
            +dataset: dev_staging
            +materialized: table
            google_calendar:
                stg_google_calendar_dim:
                    +enabled: true
            ebird:
                stg_ebird_obs:
                    +enabled: true
                stg_ebird_hotspots:
                    +enabled: true
                    +materialized: incremental
            covid:
                stg_county_cases:
                    +enabled: true
                stg_county_mask_use:
                    +enabled: true
                stg_excess_deaths:
                    +enabled: true
        intermediate:
            +dataset: dev_intermediate
            +materialized: incremental
            google_calendar:
                int_google_calendar_dim:
                    +enabled: true
            ebird:
                int_ebird_obs:
                    +enabled: true

        prod_dw:
            +dataset: "{{'dev_sandbox' if target.name == 'dev' else 'prod_dw' }}"
            +materialized: table
            google_calendar:
                google_calendar_dim:
                    +enabled: true
            ebird: 
                ebird_obs:
                    +enabled: true
            covid:
                county_cases:
                    +enabled: true

