version: 2

sources:
    - name: dev_base
      database: max-warehouse-323301
      tables:
        - name: base_google_calendar
        - name: base_ebird
    - name: covid_data
      database: bigquery-public-data
      schema: covid19_nyt
      tables:
        - name: excess_deaths
        - name: mask_use_by_county
        - name: us_counties
        - name: us_states
      schema: covid19_geotab_mobility_impact
      tables:
        - name: airport_traffic
        